apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: best-effort-vce-small
  # No resource requests/reservations.
  # Memory overcommit possible.
spec:
  # VM operator controller name for VirtualMachine class
  # is different so addition of controllerName attr with invalid
  # value makes vm operator ignore this VM CRD instance.
  # This is majorly done because vm operator doesn't have all the
  # needed capabilities to deploy ec worker vm.
  hardware:
    cpus: 4
    memory: 6Gi
----
apiVersion: v1
kind: Namespace
metadata:
  name: sdwan
---  
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: sd-wan-vm1
  namespace: sdwan
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-vce-small
  imageName: ent.box.com/shared/static/dvevhnb1u6oqxi0yphxjlfwub4hp1wza.ova
  powerState: poweredOff
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  - networkName: "sdwanmgmtpg"
    ethernetCardType: "vmxnet3"
  - networkName: "sdwanmgmtpg"
    ethernetCardType: "vmxnet3"
  - networkName: "sdwanmgmtpg"
    ethernetCardType: "vmxnet3"
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  - networkName: "sdwanmgmtpg"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    secretName: my-vm-bootstrap-data
    transport: CloudInit
---
apiVersion: v1
kind: Secret
metadata:
  name: my-vm-bootstrap-data
  namespace: sdwan
stringData:
  user-data: |
    #cloud-config
    password: velocloud
    chpasswd: { expire: False }
    ssh_pwauth: True
