# Example deployment straight from online bitnami catalog, for example:
# Copy download URL fromhttps://bitnami.com/stack/harbor/virtual-machine and use in following manifest

apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: odoo-class
spec:
  hardware:
    cpus: 4
    memory: 8Gi

---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: odoo
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: odoo-class
  #http or https location of OVA without the prefix:
  #imageName: bitnami.com/redirect/to/2461930/bitnami-harbor-2.11.0-r0-debian-12-amd64.ova
  imageName: bitnami.com/redirect/to/2461778/bitnami-odoo-17.0.20240605-r0-debian-12-amd64.ova           
  powerState: poweredOn
  networkInterfaces:
  - networkName: "internal-ecs-pg"
    ethernetCardType: "vmxnet3"
