apiVersion: v1
kind: Namespace
metadata:
  name: sdwan
---  
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: vce-ss-fixed-pg
  namespace: sdwan
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-small
  imageName: ent.box.com/shared/static/lkje8iad2xhgkfbfum5r61e5p7qhl5zi.ova
  powerState: poweredOn  
  networkInterfaces:
  - networkName: "brlink-pg"
    ethernetCardType: "vmxnet3"
  - networkName: "internal-ecs-pg"
    ethernetCardType: "vmxnet3"
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  - networkName: "internal-ecs-pg"
    ethernetCardType: "vmxnet3"
  - networkName: "internal-ecs-pg"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    secretName: my-vm-bootstrap-data
    transport: CloudInit
---
apiVersion: v1
kind: Secret
metadata:
  name: my-vm-bootstrap-data
  namespace: sdwan
stringData:
  user-data: |
    #cloud-config
    password: velocloud
    chpasswd: { expire: False }
    ssh_pwauth: True
    velocloud:
      vce: 
            vco: 152.65.224.129
            activation_code: KL42-AVNX-58Y6-DPQU
            vco_ignore_cert_errors: true
