apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: keswick-host-config
  namespace: esx-system
spec:
  layertype: Incremental
  autoStartSettings:
    enabled: true  # Enable auto start for the ESXi host
    startDelay: 60  # Delay in seconds before starting VMs after host boot
    stopDelay: 60   # Delay in seconds before stopping VMs during host shutdown
    stopAction: guestShutdown  # Action to take when stopping VMs (options: 'guestShutdown', 'powerOff')
    vmPowerOnOrder:
      - vmName: ec-worker
        priority: 1
      - vmName: ubuntu-alpr1
        priority: 2
      - vmName: ubuntu-alpr5
        priority: 2
