---
apiVersion: batch/v1
kind: Job
metadata:
  name: autostart-vm-job
  namespace: esx-system
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: autostart-vm-container
        image: your-docker-image:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Executing AutoStart Commands"
          vim-cmd hostsvc/autostartmanager/enable_autostart 1
          vim-cmd hostsvc/autostartmanager/update_defaults 2 2
          echo "Completed Host AutoStart --- Suresh"
          # Get all VMIDs, skipping the header, and ignore the first value
          vm_ids=$(vim-cmd vmsvc/getallvms | tail -n +2 | awk '{print $1}')

          # Define other parameters for autostartmanager/update_autostartentry
          power_on="PowerOn"
          default="systemDefault"
          priority=1  # You can adjust the initial priority

          # Loop through each VMID
          for vm_id in $vm_ids; do
              # Execute the update_autostartentry command
              vim-cmd hostsvc/autostartmanager/update_autostartentry "$vm_id" "$default" 2 "$priority" 2 2 "$default"
              # Increment priority for the next VM
              priority=$((priority + 1))
          done
      imagePullPolicy: Always
  backoffLimit: 3
