#example deployment and post customsiation for Photon VM
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ubuntu-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: guaranteed-small
  #imageName: packages.vmware.com/photon/4.0/GA/ova/photon-hw11-4.0-1526e30ba0.ova
  imageName: cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    configMapName: user-data-ubuntu
    transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-ubuntu
    namespace: default
data:
  user-data: |
    #cloud-config
    ssh_pwauth: true
    allow-pw-auth: true
    users:
      - name: ubuntu
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        #passwd: '$6$rounds=4096$g4hhnNzlgGol6ghX$E.Qu.vzMA.qzufAhwI84THkFSTjGCTognWAiSt8uioMKjKDUF1wPtIAiKaSyIaT/JuunlWk8pDetIgYLT81Nr0'
        passwd: 'VMware1!'
        shell: /bin/bash
    write_files:
      - content: |
          Keswick VM service says Hello World
        path: /helloworld
