apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ubuntu-vm
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: guaranteed-small
  imageName: cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    configMapName: user-data-ubuntu
    transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-ubuntu
    namespace: default
data:
  user-data: |
    #cloud-config
    ssh_pwauth: true
    users:
      - name: ubuntu
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        passwd: 'VMware1!'
        shell: /bin/bash
    write_files:
      - content: |
          Keswick VM service says Hello World
        path: /helloworld
