apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ubuntu-alpr1
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: my-vm-class1
  imageName: cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "AppVMs"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    configMapName: user-data-ubuntu-1
    transport: CloudInit

---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: my-vm-class1
spec:
  configSpec:
    _typeName: VirtualMachineConfigSpec
    cpuAllocation:
      _typeName: ResourceAllocationInfo
      limit: 2200
      reservation: 200
    memoryAllocation:
      _typeName: ResourceAllocationInfo
      limit: 2048
      reservation: 1024
  hardware:
    cpus: 1
    memory: 2Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-ubuntu-1
    namespace: default
data:
  user-data: |
    #cloud-config
    ssh_pwauth: true
    users:
      - name: ubuntu
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        passwd: '$6$lFpuphQWRsDXvAZA$mr3VKKx8l2TnladSXMfztX6D6mNwJyLNYsvmUevSWNWVQuP1YlD7pQJzFjkgzj6ISL4bo7TF8bQAUdWr9IHGE1'
        shell: /bin/bash
    runcmd:
      - sudo rm -f /etc/netplan/*.yaml
      - |
        cat <<EOF > /etc/netplan/50-cloud-init.yaml
        network:
            ethernets:
                ens192:
                    dhcp4: true
            version: 2
        EOF
      - sudo netplan apply
      - |
        cat <<EOF > /home/ubuntu/install-script.sh
        sudo sleep 60
        sudo apt-get update
        sudo apt install -y make cmake apache2
        sudo apt-get install -y python3-opencv openalpr g++ cmake libtesseract-dev libleptonica-dev libopencv-dev  libcurl4-openssl-dev liblog4cplus-dev
        sudo git clone https://github.com/openalpr/openalpr.git
        cd openalpr/
        cd src
        sudo mkdir build
        cd build
        sudo cmake ..
        sudo make
        sudo make install
        sudo cp /usr/share/openalpr/runtime_data/ocr/tessdata/* /usr/share/openalpr/runtime_data/ocr/
        sudo sleep 20
        sudo wget http://plates.openalpr.com/h786poj.jpg
        alpr -c eu h786poj.jpg > /tmp/alpr-result.txt
        EOF
      - sudo chmod +x /home/ubuntu/install-script.sh
      - sudo sh /home/ubuntu/install-script.sh &
      - sudo systemctl enable apache2
