apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ubuntu-alpr4
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: guaranteed-small
  imageName: cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    configMapName: user-data-ubuntu-4
    transport: CloudInit
  
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-ubuntu-4
    namespace: default
data:
  user-data: |
    #cloud-config
    ssh_pwauth: true
    users:
      - name: ubuntu
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        passwd: '$6$lFpuphQWRsDXvAZA$mr3VKKx8l2TnladSXMfztX6D6mNwJyLNYsvmUevSWNWVQuP1YlD7pQJzFjkgzj6ISL4bo7TF8bQAUdWr9IHGE1'
        shell: /bin/bash
    write_files:
      - content: |
          Keswick VM service says Hello World
        path: /helloworld
    runcmd:
      - sudo rm -f /etc/netplan/*.yaml
      - |
        cat <<EOF > /etc/netplan/50-cloud-init.yaml
        network:
            ethernets:
                ens192:
                    dhcp4: true
            version: 2
        EOF
      - sudo netplan apply
      - |
        cat <<EOF > /home/ubuntu/install-script.sh
        sudo apt-get update
        sudo apt install -y make cmake apache2
        sudo apt-get install -y python3-opencv openalpr g++ cmake libtesseract-dev libleptonica-dev libopencv-dev  libcurl4-openssl-dev liblog4cplus-dev
        sudo git clone https://github.com/openalpr/openalpr.git
        cd openalpr/
        cd src
        sudo mkdir build
        cd build
        sudo cmake ..
        sudo make
        sudo make install
        sudo cp /usr/share/openalpr/runtime_data/ocr/tessdata/* /usr/share/openalpr/runtime_data/ocr/
        EOF
      - sudo chmod +x /home/ubuntu/install-script.sh
      - sudo sh /home/ubuntu/install-script.sh &
      - sudo wget http://plates.openalpr.com/ea7the.jpg
      - sudo systemctl enable apache2
      - alpr -c us ea7the.jpg > /tmp/alpr-result.txt
      - ls -ltr >> /tmp/alpr-result.txt
